'use strict';

/**
 * Moves unreferenced site files out of IAMSREE/ and into attic/.
 *
 *   node tools/prune-assets.js           show what would move
 *   node tools/prune-assets.js --apply   move them
 *
 * Moves rather than deletes: this project has no commits, so a delete cannot be
 * undone. attic/ is git-ignored and outside the served directory, so the files
 * leave both the site and the static export but stay on disk. Delete attic/ by
 * hand once you are satisfied nothing is missing.
 *
 * Editor droppings (.DS_Store) are deleted outright - nothing is lost.
 */

const fs = require('fs');
const path = require('path');

const { config } = require('../app/config');

const APPLY = process.argv.includes('--apply');
const ATTIC = path.join(config.paths.root, 'attic');

/** Deleted outright: generated by the OS, never part of the site. */
const JUNK = [/(^|\/)\.DS_Store$/];

/**
 * Moved to the attic. Each entry says why, so the list can be argued with
 * rather than taken on trust.
 */
const PRUNE = [
  { pattern: /^js\/img-\d+\.webp$/, why: 'image sitting in the script directory' },
  { pattern: /^images\/logo-brand-\d+\.webp$/, why: 'placeholder logo from the original template' },
  { pattern: /^images\/img-(101|103|106)\.webp$/, why: 'template image the site never used' },
  { pattern: /^images\/(back|custom)\.png$/, why: 'not referenced by any page or record' },
  { pattern: /^images\/(edit|in)\.jpeg$/, why: 'not referenced by any page or record' },
  { pattern: /^images\/image\.png_2K_\d+\.jpe?g$/, why: 'not referenced by any page or record' },
  { pattern: /^images\/Cartoon_characters_.*\.mp4$/, why: 'not referenced by any page or record' },
  { pattern: /^images\/smallsree$/, why: 'extensionless file, not referenced by any page or record' }
];

function siteFiles() {
  const out = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (full !== config.paths.uploads) walk(full);
      } else {
        out.push(path.relative(config.paths.site, full).split(path.sep).join('/'));
      }
    }
  })(config.paths.site);
  return out;
}

let movedBytes = 0;
let moved = 0;
let deleted = 0;

for (const rel of siteFiles().sort()) {
  const source = path.join(config.paths.site, rel);

  if (JUNK.some((p) => p.test(rel))) {
    console.log(`  delete  ${rel}`);
    if (APPLY) fs.rmSync(source, { force: true });
    deleted += 1;
    continue;
  }

  const rule = PRUNE.find((r) => r.pattern.test(rel));
  if (!rule) continue;

  const size = fs.statSync(source).size;
  movedBytes += size;
  moved += 1;
  console.log(`  attic   ${rel}  (${(size / 1024).toFixed(0)} KB) - ${rule.why}`);

  if (!APPLY) continue;
  const target = path.join(ATTIC, rel);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.renameSync(source, target);
}

console.log();
console.log(
  `${deleted} file(s) ${APPLY ? 'deleted' : 'to delete'}, ` +
    `${moved} file(s) (${(movedBytes / 1048576).toFixed(1)} MB) ${APPLY ? 'moved to attic/' : 'to move to attic/'}.`
);
if (!APPLY) console.log('Re-run with --apply to make the changes.');
